### ISSUE TITLE
Task #136 - implementation de la methode update() dans salleDAO.java

### ISSUE THREAD

**Issue by ghost** [psnpsn/GEcole#32]
- **User Story** : 23
- **Tâche ID**    : 136
- **Temps d'acheminement** :  2 _heures._

**Description Tache** : implementation concrete de la methode `update()` dans la classe` salleDAO.java`

**Comment by Huronymos** [comment]
Tache Terminer -> Huronymos/GEcole@beaea7040d26e8cff0b9db51d84f81f124b03ef9

**Comment by ghost** [comment]
Tache Terminer --> Huronymos@e7a92133ca03b743477b087a3db5d41535746a35
